name: dockerserver

on:
  push:
    branches:
      - main

jobs:
  docker-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version
