name: hello

on:
  workflow_dispatch: 
    
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello user
        run: echo "hello bhai"

      - name: say username
        run: echo "hello username $USER"
        
  details:
     runs-on: ubuntu-latest
     steps:
       - name: show version docker, python
         run: docker --version && python --version
