name: sumit

on:
    push:
        branches:
          - main
jobs:
   greet:
           runs-on: ubuntu-latest
           steps:
               - name: print my run-name
                 run: echo "MY NAME IS SUMIT"
               - name: enter the age
                 run: echo "MY AGE IS 23"
